### PR TITLE
Add support for DPT 251.600 (6 byte RGBW).

### PR DESCRIPTION
**Pull request by phbaer**
Maybe that additional DPT for lights might be useful to others as well. Tested with MDT SCN-DALI16.03.

### CODE REVIEW

**Comment by marvin-w** [comment]
LGTM besides the fact that the light class is going to blow up.

Maybe @farmio can have a look.

**Comment by farmio** [comment]
Looks good to me too, but I have no   colored lights so can't test it ¯\_(ツ)_/¯ 
I think we would have all knx light possibilities covered now 🤓

Adding it to the hass-component would be fine.

**Comment by phbaer** [comment]
Blow up: yes, unfortunately. Also though of merging it with the generic colour propery but ... well, it's basically a low-level interface to KNX and hence different DPTs should not be hidden in that case.

The HASS component is on my list. Need to find some spare time later this week.

**Comment by phbaer** [comment]
As the integration in home assistant is easier with a combined RGB/RGBW interface, I changed the xknx light implementation accordingly. This slightly reduces the light.py blowup...

Also the underlying DPT abstraction now only returns the colour+white values and keeps the management bits hidden. If a colour or the white value are invalid, they'll be set to the previously received value or 0.

I'd be done for now.

**Pull request merged**
