### PR TITLE
Drop support for python 3.8

### PR DESCRIPTION
**Pull request by marvin-w**
## Description

Follow upstream and remove support for Python 3.8

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have performed a self-review of my own code
- [x] The documentation has been adjusted accordingly
- [x] The changes generate no new warnings
- [x] Tests have been added that prove the fix is effective or that the feature works
- [x] The changes are documented in the changelog
- [x] The Homeassistant plugin has been adjusted in case of new config options

### CODE REVIEW

**Comment by rnixx** [comment]
No one gets hurt keeping support for older python versions but the people depending on older python versions.

I don't really understand the mood of dropping python versions without real benefits. IMO projects should support python versions until they are EOL except there is a good reason to do otherwise (which i don't see here).

**Comment by marvin-w** [comment]
> No one gets hurt keeping support for older python versions but the people depending on older python versions.
> 
> I don't really understand the mood of dropping python versions without real benefits. IMO projects should support python versions until they are EOL except there is a good reason to do otherwise (which i don't see here).

This library is mainly used in Home Assistant, which dropped support for 3.8 here: https://github.com/home-assistant/core/pull/63883.

We usually try to go the same route.

**Comment by rnixx** [comment]
> This library is mainly used in Home Assistant

well, at least i use it outside home assistant

**Comment by rnixx** [comment]
> Nevertheless this is a hobby project

Everyone is appreciating the contributor's efforts and hard work. The fact that your commitment is for fun not necessarily implies the same for everyone.
 
xknx is currently the only serious python KNX implementation, and maintenance and backwards compatibility are important parts of software development.

> Imho keeping the liabilities of older versions just for the sake of it, with probably <0,4% of our users even recognising, would be counterproductive to development progress, speed and delight.

This is ignorant at best. Keeping B/C is nothing harmful, cosmetic reasons are no excuse for breaking things.

> That said, we love that some are using xknx outside of Home Assistant and don't want to drive anyone away.

The potential userbase for KNX with python is small, and it would be sad if those few users disperse instead of focus on a promising project. Over time, software should tend to get major at some place. If the goal of the project is to have a sandbox to play around, please state this with big fat letters in your documentation.

**Comment by rnixx** [comment]
> That's cool! May I ask what hinders you to simply update to a more recent python version?

Sure. A huge codebase. Conservative Upgrade policy. Time.

**Comment by marvin-w** [comment]
> > That's cool! May I ask what hinders you to simply update to a more recent python version?
> 
> Sure. A huge codebase. Conservative Upgrade policy. Time.

The only valid point here is the conservative upgrade policy. Everything else is and should not be a real reason not to upgrade.

> > Nevertheless this is a hobby project
> 
>  maintenance and backwards compatibility are important parts of software development.

True, that's why we have decided to follow the Home Assistant upgrade policy in order to keep maintenance efforts at a minimum, because yes, it takes time to upgrade to a new version but on the other side it also takes time to maintain (old) software. 

> 
> This is ignorant at best. Keeping B/C is nothing harmful, cosmetic reasons are no excuse for breaking things.
> 
> The potential userbase for KNX with python is small, and it would be sad if those few users disperse instead of focus on a promising project. Over time, software should tend to get major at some place. If the goal of the project is to have a sandbox to play around, please state this with big fat letters in your documentation.

I find this quite harsh. Change is nothing bad. As we have previously said, we follow the Home Assistant upgrade policy. If you or your company (this is what it sounds like to me) have any issues with that please reach out, we setup a support contract and will find a solution for it.

I also don't see why adding support for newer python versions and dropping older versions should hinder us, in any way, of getting to a major state for XKNX at a given point in time.

Additional information can otherwise also be found in our license.

**Comment by rnixx** [comment]
> I find this quite harsh

yes it is, as well as telling other people that their problems or reasons for doing one thing or another not even exist. It was not intended to insult anyone.

> Change is nothing bad.

Sure not. Neither is taking care about several aspects of one's user base. B/C is nowadays easy to handle with all the shiny CI tools.

Maybe I'm just too accustomed on taking care about this topic from other projects, my fault. You're doing a great job either way.

**Comment by marvin-w** [comment]
> > I find this quite harsh
> 
> yes it is, as well as telling other people that their problems or reasons for doing one thing or another not even exist. 

What I meant was that the other two reasons are easier to overcome than the upgrade policy that someone of your org has given you.

> It was not intended to insult anyone.

Same for me.

> 
> > Change is nothing bad.
> 
> Sure not. Neither is taking care about several aspects of one's user base. B/C is nowadays easy to handle with all the shiny CI tools.

Yes, and we still support python 3.9 and 3.10 - and when 3.11 will be released we will support that as well.

**Pull request merged**
