### PR TITLE
Avoid leaking ValueError exception on unknown APCI command

### LINKED ISSUE #226: ValueError: [448,256] is not a valid APCICommand
**Description of problem:**
Exception during processing of messages, likely while ETS is communicating with new Secure IP Interface.

- [ ] using xknx standalone
- [X] using Home-Assistant knx plugin

**Version information:**
- xknx / Home-Assistant release with the issue: 0.98
- last working xknx / Home-Assistant release (if known): None

**KNX installation:**

ETS 5.7.2

**Problem-relevant `xknx.yaml` or `configuration.yaml` entries (fill out even if it seems unimportant):**

**Traceback (if applicable):**
```
Aug 19 19:09:24 hass hass[32967]: Traceback (most recent call last):
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
Aug 19 19:09:24 hass hass[32967]:     self._callback(*self._args)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/asyncio/selector_events.py", line 1078, in _read_ready
Aug 19 19:09:24 hass hass[32967]:     self._protocol.datagram_received(data, addr)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/io/udp_client.py", line 55, in datagram_received
Aug 19 19:09:24 hass hass[32967]:     self.data_received_callback(data)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/io/udp_client.py", line 87, in data_received_callback
Aug 19 19:09:24 hass hass[32967]:     knxipframe.from_knx(raw)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/knxip.py", line 78, in from_knx
Aug 19 19:09:24 hass hass[32967]:     pos += self.body.from_knx(data[pos:])
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/tunnelling_request.py", line 48, in from_knx
Aug 19 19:09:24 hass hass[32967]:     pos += self.cemi.from_knx(raw[pos:])
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/cemi_frame.py", line 113, in from_knx
Aug 19 19:09:24 hass hass[32967]:     return self.from_knx_data_link_layer(raw)
Aug 19 19:09:24 hass hass[32967]:   File "/home/homeassistant/env/lib/python3.6/site-packages/xknx/knxip/cemi_frame.py", line 143, in from_knx_data_link_layer
Aug 19 19:09:24 hass hass[32967]:     self.cmd = APCICommand(tpci_apci & 0xFFC0)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/enum.py", line 291, in __call__
Aug 19 19:09:24 hass hass[32967]:     return cls.__new__(cls, value)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/enum.py", line 533, in __new__
Aug 19 19:09:24 hass hass[32967]:     return cls._missing_(value)
Aug 19 19:09:24 hass hass[32967]:   File "/usr/lib/python3.6/enum.py", line 546, in _missing_
Aug 19 19:09:24 hass hass[32967]:     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
Aug 19 19:09:24 hass hass[32967]: ValueError: 448 is not a valid APCICommand
```

```
Aug 22 08:15:49 hass hass[35975]: ValueError: 256 is not a valid APCICommand
Aug 22 08:15:49 hass hass[35975]:     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
Aug 22 08:15:49 hass hass[35975]:   File "/usr/lib/python3.6/enum.py", line 546, in _missing_
Aug 22 08:15:49 hass hass[35975]:     return cls._missing_(value)
Aug 22 08:15:49 hass hass[35975]:   File "/usr/lib/python3.6/enum.py", line 533, in __new__
Aug 22 08:15:49 hass hass[35975]:     return cls.__new__(cls, value)
Aug 22 08:15:49 hass hass[35975]:   File "/usr/lib/python3.6/enum.py", line 291, in __call__
Aug 22 08:15:49 hass hass[35975]:     self.cmd = APCICommand(tpci_apci & 0xFFC0)
Aug 22 08:18:24 hass hass[35975]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
Aug 22 08:18:24 hass hass[35975]:     self._run_once()
Aug 22 08:18:24 hass hass[35975]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
Aug 22 08:18:24 hass hass[35975]:     self.run_forever()
Aug 22 08:18:24 hass hass[35975]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
Aug 22 08:18:24 hass hass[35975]:     return loop.run_until_complete(main)
Aug 22 08:18:24 hass hass[35975]:   File "/home/homeassistant/env/lib/python3.6/site-packages/homeassistant/util/async_.py", line 37, in asyncio_run
Aug 22 08:18:24 hass hass[35975]:     exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
Aug 22 08:18:24 hass hass[35975]:   File "/home/homeassistant/env/lib/python3.6/site-packages/homeassistant/__main__.py", line 419, in main
Aug 22 08:18:24 hass hass[35975]:     sys.exit(main())
Aug 22 08:18:24 hass hass[35975]:   File "/home/homeassistant/env/bin/hass", line 10, in <module>

```

### PR DESCRIPTION
**Pull request by elupus**
This avoid crashing homeassistant on these types of messages.

Fixes #226

### CODE REVIEW

**Comment by elupus** [comment]
Note coverage will likeley go down. But there was no tests for the CEMIFrame as far as i could tell.

**Comment by Julius2342** [comment]
Wouldn't it make more sense to handle this directly within https://github.com/XKNX/xknx/blob/master/xknx/knxip/cemi_frame.py#L143 ` (catching the value error and raising an XKNXException istead) ?

**Comment by elupus** [comment]
The exact line you mention is the line we are modifying in this pull.

**Comment by Julius2342** [comment]
Oh my fault! Sorry! \*blush\*

**Comment by elupus** [comment]
Well the whole structure was untested. So it seemed messy/large to write it. I'll see if I have some time to look at it.

**Comment by elupus** [comment]
I caught the same issue for the CEMIMessageCode too.

**Comment by elupus** [comment]
And added some tests

**Pull request merged**
