### PR TITLE
Add fan device

### PR DESCRIPTION
**Pull request by itineric**
New fan device.
Speed is a percentage value (0 to 100).

### CODE REVIEW

**Comment by itineric** [comment]
What should be done to get the checks passing ?

**Comment by Julius2342** [comment]
@itineric May I ask you to add a unit test for your new device? (esp in this case it is very important bc. i dont have fans and i need to know if i break something when i change something in the underlaying library in the future...

**Comment by itineric** [comment]
Dont understand whats wrong now...

**Comment by itineric** [comment]
I have add the hass component: https://github.com/home-assistant/home-assistant/pull/16434
Now i need to point the xknx version that includes the fan device, how/when will i be able to do that ?

**Comment by Julius2342** [comment]
@itineric we need to push a new version with all the recent changes...

**Pull request merged**
