### PR TITLE
Fix Gateway scanner on linux

### PR DESCRIPTION
**Pull request by marvin-w**
## Description

Fix GW scanner on linux.

Fixes https://github.com/home-assistant/core/issues/62467

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] The documentation has been adjusted accordingly
- [ ] The changes generate no new warnings
- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] The changes are documented in the changelog
- [ ] The Homeassistant plugin has been adjusted in case of new config options

### CODE REVIEW

**Comment by mforst2** [comment]
Unfortunately this change breaks the gateway discovery on Windows. When reverting this change gateway recovery works again.

On Windows the IP and port of the discovery_endpoint must be placed in the HPAI, not the multicast address. This is also what the ETS5 does, as you can see in the Wireshark trace:

grafik

**Comment by farmio** [comment]
From 3_8_2 Core:

> 7.6.1 SEARCH_REQUEST
The SEARCH_REQUEST frame shall be sent by a KNXnet/IP Client via multicast to the discovery endpoints of any listening KNXnet/IP Server. As communication with the discovery endpoint shall be connectionless and stateless, the KNXnet/IP Client’s discovery endpoint address information shall be included in the KNXnet/IP body.

and

> 4.2 Discovery
(...)
The discovery operation shall consist of a SEARCH_REQUEST data packet, sent via multicast using the discovery endpoint, which shall contain the HPAI of the KNXnet/IP Client’s discovery endpoint. The HPAI may contain a unicast IP address to receive the answers from the different KNXnet/IP Servers directly in a point-to-point manner. **Typically it should contain the KNXnet/IP System Setup multicast address** to ensure reception from KNXnet/IP Servers that are on a different subnetwork.

I think we are acting properly according to the specifications now. Maybe some Firewall etc. is blocking the reception of multicast packages on your system?

**Comment by mforst2** [comment]
There seems to be a problem with my KNX IP Gateway (Weinzierl 731). It only answers to SEARCH_REQUEST packets containing an unicast address in HPAI. It does not do anything on the Ethernet if a multicast address is specified.

I checked this behaviour with Wireshark on Windows 11 (Firewall disabled) and on Linux (Raspberry Pi 4 with Bullseye). Gateway was connected via an unmanaged switch and in a second test directly to the network interface of the PC/RPi.

Which KNX IP Gateways do you use for testing?

**Comment by farmio** [comment]
We have (in our productive installations) Gira, MDT and Weinzierl (777) available to test things on. 
We almost never Test things on Windows 😬

**Pull request merged**
