### PR TITLE
Remove Config v2

### PR DESCRIPTION
**Pull request by marvin-w**
## Description

Since we will drop support for config handling in xknx we should remove Config V2 again.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have performed a self-review of my own code
- [x] The documentation has been adjusted accordingly
- [x] The changes generate no new warnings
- [x] Tests have been added that prove the fix is effective or that the feature works
- [x] The changes are documented in the changelog
- [x] The Homeassistant plugin has been adjusted in case of new config options

### CODE REVIEW

**Review by farmio — APPROVED** [review]
omfg +13 -3234

**Comment by marvin-w** [comment]
Yea, kinda sad I wasted so much time with this :dancers:

**Comment by spacegaier** [comment]
Just wondering: Could it be made possible for the HA YAML format to be used for non-HA use cases as well, so that all users that run XKNX standalone and currently use the old config file, could migrate to that as a fallback? Otherwise standalone users are now forced to do everything in Python code?

**Comment by marvin-w** [comment]
@spacegaier There is already a migration tool available here: https://xknx.io/config_converter.html

From XKNX Standalone -> HA YAML.

We do not plan to support standalone yaml configuration in the future as we would have to replicate the already existing configuration scheme causing double maintenance effort. Reusing the schema and config is also not possible as HA would not allow it.

**Pull request merged**
