### PR TITLE
Use upper case L for liter

### PR DESCRIPTION
**Pull request by elupus**
This matches unit used in home assistant.

## Description

The unit used for liters in home assistant is upper case L. So let's provide that as default.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] The documentation has been adjusted accordingly
- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] The changes are documented in the changelog (docs/changelog.md)

### CODE REVIEW

**Comment by farmio** [comment]
🤔 should we attempt to move device class definitions and units (overrides as they are defined in KNX specs as well) to the HA integration so such changes can be done in batches in the core repo?

We could also add "convenience types" to eg. have state_class set. 
cc @marvin-w

**Comment by elupus** [comment]
Yup, we likely should have the mapping of this inside home assistant instead of in the KNX library. Do you feel we should stick to KNX spec here and try to work around it inside home assistant for now? I don't think we have the arch in place at the moment?

**Comment by farmio** [comment]
Nah, we can always revert back to Knx spec specifics later when we have such thing in place. 

I'm just preparing a bugfix PR - we can release this probably next week then.

**Comment by marvin-w** [comment]
I don't see any issue with this PR. We don't use this anywhere anyway except HA.

**Review by marvin-w — APPROVED** [review]
Looks good!

**Pull request merged**
