### PR TITLE
[WIP] Better handle errors for ConnectResponse e.g. E_NO_MORE_CONNECTIONS

### PR DESCRIPTION
**Pull request by uweswrtz**
If status_code of response is other than E_NO_ERROR the from_knx method of ConnectResponse returns the wrong pos. That raises an (ugly) exception and the real status/error code is not returned to the user.

With this small change also other errors like E_NO_MORE_CONNECTION are handled. So at least the status code can be returned to the user.

### CODE REVIEW

**Comment by Julius2342** [comment]
Thank you for your contribution! May we ask you to adopt the unit tests too and provide a unit test for this specific behavior?

**Comment by uweswrtz** [comment]
I will try to create/adapt/change the unit tests. 

It's interesting why the current unit test fails. Looks like the test data doesn't contain HPAI while my IP GW (loxone) returns HPAI in case of E_NO_MORE_CONNECTION.

Bildschirmfoto 2020-03-27 um 14 45 31

**Comment by farmio** [comment]
Hi 👋
If it is any help, my Gira X1 also returns HPAI with E_NO_MORE_CONNECTION, whereas my MDT Router doesn't. I have attached a capture of the error from these devices.

Afaik Loxone gateway isn't a certified knx device, but it seems to behave closer to the standard than MDT 🙃

Bildschirmfoto 2020-03-27 um 21 31 21
Bildschirmfoto 2020-03-27 um 21 44 51

**Comment by uweswrtz** [comment]
I'm aware of the Loxone and KNX situation ;)

To summarize:

- Gira: sends HPAI and CDR
- Loxone: sends HPAI and CDR; but CDR is all zero - even length byte
- MDT: looks like HPAI and CDR are all zero; length according header doesn't match knx packet size (8 vs. 18)

...what a mess. I couldn't find any details in the specs, but I would assume HPAI and CDR mandatory.
Bildschirmfoto 2020-03-27 um 22 33 28

I would say it's not useful or helpful to parse packets if status is error under these circumstances. My code changes do just this. They count just the bytes so that ConnectResponse.from_knx returns the correct length/pos and KNXIPFrame.from_knx can compare this value against the header.

But I assume this will still fail for MDT (because header length value and knx packet length seem to not match)

**Comment by uweswrtz** [comment]
I added unit tests for gira, mdt and loxone.
ConnectResponse.to_knx and ConnectResponse.calculated_length do not work with ErrorCode.E_NO_MORE_CONNECTIONS. So creating packets in the test is not possible at the moment.
These methods are implemented for ErrorCode.E_NO_ERROR only.
I tried to fix this, but then unit test  "test_connect_response_connection_error" will fail.
@Julius2342 you implemented this test? For the raw test data there is no HPAI and and CDR in the body. Is this the behavior of a real vendor?

**Comment by Julius2342** [comment]
> @Julius2342 you implemented this test? For the raw test data there is no HPAI and and CDR in the body. Is this the behavior of a real vendor?

Don't remember. Might be that i added the unit test with crafted data. So feel free to change the testcase.

**Comment by uweswrtz** [comment]
What changed:

- _ConnectResponse.calculated_length()_ return value always includes HPAI and CRD 
(According to Chapter 3/8/4 "Tunneling" (KNXnet/IP) Section 4.4.4 CRD is 4 Bytes and 
Chapter 3/8/2 "Core" (KNXnet/IP) Section 7.8.2 Connect Response contains HPAI and CRD data)

- _ConnectResponse.from_knx()_ returns pos(length) of all data bytes if not ErrorCode.E_NO_ERROR, but doesn't parse HPAI and CRD

- Replaced test _test_connect_response_connection_error_ for ConnectResponse with 3 test with real data from Gira, MDT and Loxone for ErrorCode.E_NO_MORE_CONNECTIONS

@farmio Would be nice to see the result for MDT :smiley:

**Comment by farmio** [comment]
MDT:
```
DEBUG:xknx.log:Starting tunnel from 10.1.1.9 to 10.1.2.40:3671
DEBUG:xknx.knx:Sending: <KNXIPFrame <KNXIPHeader HeaderLength="6" ProtocolVersion="16" KNXIPServiceType="KNXIPServiceType.CONNECT_REQUEST" Reserve="0" TotalLength="26" />
 body="<ConnectRequest control_endpoint="<HPAI 10.1.1.9:65047 />" data_endpoint="<HPAI 10.1.1.9:65047 />" request_type="ConnectRequestType.TUNNEL_CONNECTION" />" />
DEBUG:xknx.knx:Received: <KNXIPFrame <KNXIPHeader HeaderLength="6" ProtocolVersion="16" KNXIPServiceType="KNXIPServiceType.CONNECT_RESPONSE" Reserve="0" TotalLength="8" />
 body="<ConnectResponse communication_channel="0" status_code="ErrorCode.E_NO_MORE_CONNECTIONS" control_endpoint="<HPAI 0.0.0.0:0 />" request_type="None" identifier="None" />" />
WARNING:xknx.log:Error: KNX bus responded to request of type 'Connect' with error in 'ConnectResponse': ErrorCode.E_NO_MORE_CONNECTIONS
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "main.py", line 40, in main
    await xknx.start(connection_config=connection_config, daemon_mode=True)
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/xknx.py", line 76, in start
    await self.knxip_interface.start()
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/knxip_interface.py", line 102, in start
    self.connection_config.auto_reconnect_wait)
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/knxip_interface.py", line 144, in start_tunnelling
    await self.interface.start()
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/tunnel.py", line 83, in start
    await self.connect()
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/tunnel.py", line 104, in connect
    raise XKNXException("Could not establish connection")
xknx.exceptions.exception.XKNXException: Could not establish connection
```

**Comment by uweswrtz** [comment]
Not really what I expected 😒 Now I recognized I had additional exception handling in my test code. 

This will need some more work...

**Comment by farmio** [comment]
it seems to be the same on a Gira Router:
```
DEBUG:xknx.log:Starting tunnel from 10.1.1.9 to 10.1.0.40:3671
DEBUG:xknx.knx:Sending: <KNXIPFrame <KNXIPHeader HeaderLength="6" ProtocolVersion="16" KNXIPServiceType="KNXIPServiceType.CONNECT_REQUEST" Reserve="0" TotalLength="26" />
 body="<ConnectRequest control_endpoint="<HPAI 10.1.1.9:65475 />" data_endpoint="<HPAI 10.1.1.9:65475 />" request_type="ConnectRequestType.TUNNEL_CONNECTION" />" />
DEBUG:xknx.knx:Received: <KNXIPFrame <KNXIPHeader HeaderLength="6" ProtocolVersion="16" KNXIPServiceType="KNXIPServiceType.CONNECT_RESPONSE" Reserve="0" TotalLength="8" />
 body="<ConnectResponse communication_channel="0" status_code="ErrorCode.E_NO_MORE_UNIQUE_CONNECTIONS" control_endpoint="<HPAI 0.0.0.0:0 />" request_type="None" identifier="None" />" />
WARNING:xknx.log:Error: KNX bus responded to request of type 'Connect' with error in 'ConnectResponse': ErrorCode.E_NO_MORE_UNIQUE_CONNECTIONS
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "main.py", line 40, in main
    await xknx.start(connection_config=connection_config, daemon_mode=True)
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/xknx.py", line 76, in start
    await self.knxip_interface.start()
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/knxip_interface.py", line 102, in start
    self.connection_config.auto_reconnect_wait)
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/knxip_interface.py", line 144, in start_tunnelling
    await self.interface.start()
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/tunnel.py", line 83, in start
    await self.connect()
  File "/Users/meti/Documents/Dev/xknx-xknx/xknx/xknx/io/tunnel.py", line 104, in connect
    raise XKNXException("Could not establish connection")
xknx.exceptions.exception.XKNXException: Could not establish connection
```

**Comment by uweswrtz** [comment]
At least the correct waring: _WARNING:xknx.log:Error: KNX bus responded to request of type 'Connect' with error in 'ConnectResponse': ErrorCode.E_NO_MORE_UNIQUE_CONNECTIONS_
is nice. 😀 

The "Could not establish connection" exception is raised if connect is not a successful.
Because everything except ErrorCode.E_NO_ERROR is a error that's all correct.

In general the current approach below xknx.start() is (in most cases): everything is successful or you get an exception. Changing this probably causes change to the API. At the moment everyone can assume when xkxn.start is done without an exception, everything is working.

**Pull request closed without merging**
