### PR TITLE
Implement support to automatically reconnect KNX/IP tunnel

### PR DESCRIPTION
**Pull request by rnixx**
Hi,

this PR adds support to automatically reconnect to a KNX/IP tunnel if connection cannot be established.

This is useful if connection gets lost for some reason and reconnecting via the heartbeat mechanism fails because the connection cannot be established. If so, the service hangs in a broken state and will not come back up automatically.

### CODE REVIEW

**Comment by elupus** [comment]
Yea this would really be needed. I get extremely strange error messages out of xknx in these cases too. weird parsing errors.

**Comment by rnixx** [comment]
Hi, any news on this one?

**Comment by rnixx** [comment]
oh, just seen there are conflicts.

**Comment by Julius2342** [comment]
Are you able to solve them? (Just had a look and it looks easy to fix).

**Comment by rnixx** [comment]
sure, just need to finish some daily business stuff first

**Comment by rnixx** [comment]
@Julius2342 Hi, I resolved the conflicts and further fixed a bug leaving open file descriptors from udp_client.

**Comment by rnixx** [comment]
@Julius2342 Hi, did you had time to take a look?

**Comment by Julius2342** [comment]
Thank you very much! (and sorry for the delay while reviewing)

**Comment by rnixx** [comment]
Thank you!

**Comment by rnixx** [comment]
Well, the code ``'xknx' in self`` is not from me. anyway. Since ``self.xknx`` gets set in ``UDPClientFactory.__init__``, but it may be ``None`` i guess, ``if self.xknx`` should do the trick.

I Opened a PR for the pylint error fix(es) here https://github.com/XKNX/xknx/pull/132

**Pull request merged**
