### PR TITLE
Move tunable white to color temperature with mode, add absolute temp

### LINKED ISSUE #403: Problem with light color_temperature -> knx device uses wrong DPT
Hi,

I'm using the ISE smart connect KNX Hue (https://www.ise.de/de/produkte/ise_smart_connect_KNX_Hue) to control my Hue lamps in HA.

The problem is the KNX device uses DPT 9.002 (2 byte relative Kelvin) and not DPT 7.600
image

Unfortunately the datatypes are not compatible.

Is there a possibility to convert the types in HA or is there a code change in xknx needed?

### PR DESCRIPTION
**Pull request by crazyfx1**
## Description

As suggested in #698, move tunable white to color temperature and add a mode as parameter.
I also sneaked in another mode for my problem with wrong DPT and thus this fixes #403

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] I have performed a self-review of my own code
- [x] The documentation has been adjusted accordingly
- [x] The changes generate no new warnings
- [x] Tests have been added that prove the fix is effective or that the feature works
- [x] The changes are documented in the changelog
- [x] The Homeassistant plugin has been adjusted in case of new config options

### CODE REVIEW

**Comment by crazyfx1** [comment]
I'm not sure how to increase coverage and I can't see the coverage report :(

**Comment by crazyfx1** [comment]
Yes, a year ago I contacted them. They acknowledged that they use the wrong DPT and they might change it if they plan another update. But I have no hope that this will ever be fixed, since there was not a single update since I bought the device.

Well currently I'm changing the code after every HA update. So after each update, I have to ssh to HA, connect to the docker container and change the light.py file manually to RemoteValueTemp and restart.

**Comment by crazyfx1** [comment]
@farmio @marvin-w can we get a final decision here? :)

**Comment by farmio** [comment]
I am still not in favour of adding and maintaining functions to circumvent bugs of single manufacturers firmwares - as this is clearly expected DPT7 from the KNX specs.

With the addition of decoded payloads in knx_event (https://github.com/home-assistant/core/pull/57621) I think your problem can be solved from within HA by an automation (or blueprint) translating DPT9 to DPT7 (and vice versa).

**Pull request closed without merging**
