### PR TITLE
Update HA Device Classes

### LINKED ISSUE #1179: HA device class CURRENT missing
**Description of problem:**

- [ ] using xknx standalone
- [x] using Home-Assistant knx integration

Hi, since home assistant 2023.1 A and mA can be converted via the user user interface. I noticed that this is not possible with KNX integration as the CURRENT device class is not automatically set.
I have defined it manually, okay for me, however I was just wondering why this is not done automatically...
Maybe there are other device classes missing in the meantime as well, did not yet check it (typing on my mobile phone).

As always great work 👍

### PR DESCRIPTION
**Pull request by KNXBroker**
## Description

I have added the following home assistant device classes which could be clearly assigned to KNX DPTs:
- voltage
- current
- distance
- frequency
- weight
- speed
- apparent_power
- wind_speed

Furthermore I have corrected device class 'illuminance'. 
- Added  to 7.013 brightness (lx)
- Removed from 14.41 luminance (cd/m²), 14.42 luminous_flux (lm) and 14.43 luminous_intensity (cd).  These DPTs do not match with HA illuminance unit of measurement lx. Starting HA 2023.1 Home Assistant is rising a warning if device_class unit of measurement does not match with the entity's unit of measurement. Example: `Entity sensor.example (<class 'homeassistant.components.knx.sensor.KNXSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+knx%22`

I did not find any test in XKNX. Please advice if and where to add tests. Thank you....

Fixes #1179 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests

## Checklist

- [ ] The documentation has been adjusted accordingly
- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] The changes are documented in the changelog (docs/changelog.md)

### CODE REVIEW

**Comment by KNXBroker** [comment]
Yes I saw all these tests, but not all ha_device_classes are tested. Furthermore I'm not sure if it makes sense testing the classes without home assistant itself... but I'm not a software engineer...

I think I found my mistake (shall be `assert weather._wind_speed.ha_device_class == "wind_speed"`) https://github.com/XKNX/xknx/blob/d9e94ea79b7ee9730e678eacfd638f133b33bde1/test/devices_tests/weather_test.py#L137

Please advice if it is enough to get the existing tests running or if additional tests have to be defined. For the second I'm not sure if I'm able to manage it locally, as I tried to setup a test environment without success.

**Comment by farmio** [comment]
I guess for this it is ok to just fix the existing tests.

To get a test env it should be enough to install tox https://tox.wiki/en/latest/installation.html - but this takes a bit longer to run.
You can also just `pip install -r requirements/testing.txt` (see https://github.com/XKNX/xknx#development). This should install tox as well as pytest so you can run `pytest test/dpt_tests/`

**Comment by KNXBroker** [comment]
Test is corrected, I tried to get tox running under windows, which was most likely not the best idea...

**Review by farmio — APPROVED** [review]
Thank you very much 👍

**Pull request merged**
